/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_twentyfour_JniClient */

#ifndef _Included_com_example_twentyfour_JniClient
#define _Included_com_example_twentyfour_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_twentyfour_JniClient
 * Method:    getCards
 * Signature: (IIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_twentyfour_JniClient_getCards(
		JNIEnv *, jclass, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
